# Generated by Django 3.0.6 on 2020-05-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rent_payee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_email', models.EmailField(max_length=254)),
                ('p_name', models.CharField(max_length=100)),
                ('p_country', models.CharField(max_length=100)),
            ],
        ),
    ]
